# Generated by Django 5.0.1 on 2024-09-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Resources',
        ),
    ]
