# Generated by Django 5.0.1 on 2024-09-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
