# Generated by Django 5.0.1 on 2024-09-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managements',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='managements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='management/'),
        ),
    ]
