# Generated by Django 5.0.1 on 2024-09-30 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_managements_priority_alter_managements_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='managements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
