# Generated by Django 5.0.1 on 2024-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_managements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='management_image/'),
        ),
    ]
